# Generated by Django 2.2.1 on 2019-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quanxian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuoming', models.CharField(max_length=100)),
            ],
            options={
                'permissions': (('part', '部分权限'), ('all', '全部')),
            },
        ),
    ]
